### ISSUE TITLE
[Bug] Can't interact with blocks

### ISSUE THREAD

**Issue by IFedor-F** [sisby-folk/swingthrough#2]
Can't interact with blocks in some places if there are entities behind the blocks
![image](https://github.com/sisby-folk/swingthrough/assets/116349244/4b038e38-37fe-4748-b04a-0891598fca96)

**Comment by sleepingdragoninn** [comment]
that's weird. should only be on blocks with an empty collision shape - I'll test barrels. what mc version?

**Comment by sleepingdragoninn** [comment]
Seems like I can reproduce it on 1.20.1 by doing exactly what you've done above. 

The problem is kind of a vanilla bug, kind of an us oversight - basically extending the entity raycast unconditionally means certain entities like armor stands are allowed to insist that they're closer than the block you're looking at. 

So, simple solution - run the block condition earlier so that it doesn't extend the raycast range if the block isn't transparent.

![image](https://github.com/sisby-folk/swingthrough/assets/55819817/5966afce-78ee-4846-9379-2e06cbf5fcc9)

![image](https://github.com/sisby-folk/swingthrough/assets/55819817/2e4241fa-4100-404d-b14b-b0bcbf43932c)

Thanks for the catch! Out as 1.0.4 now.

**Comment by IFedor-F** [comment]
thanks!
